### PR TITLE
LRQA-63260 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63260

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @calvinctvo ,

Please, see my comments on [LRQA-63260](https://issues.liferay.com/browse/LRQA-63260) and let me know if you have any questions.

Thanks!

**Pull request closed without merging**
