### PR TITLE
LRQA-63305 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63305
AppBuilderWorkflow#CancelCreationOfTableView

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon , thanks for your commit. I fixed the conflicts here: https://github.com/rodrigocunhaa/liferay-portal/pull/305

Great job!

**Pull request closed without merging**
