### PR TITLE
Objects Automated Test - LPS-147769, LPS-147770, LPS-147771 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-147769
https://issues.liferay.com/browse/LPS-147770
https://issues.liferay.com/browse/LPS-147771

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Manually forwarded: https://github.com/brianchandotcom/liferay-portal/pull/114505

**Pull request closed without merging**
