### PR TITLE
Workflow Automated Test - LRQA-68330 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Had to update PROCESS_DETAILS_REVISION_BY_ROW path, according to the changes on this pr:
https://github.com/rodrigocunhaa/liferay-portal/pull/724/commits/c8f8b3ac139efe3aeac4ec5658c5f8861b3c3c0f

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Combined and sent in [104425](https://github.com/brianchandotcom/liferay-portal/pull/104425)

**Pull request closed without merging**
