### PR TITLE
LPS-137942 Include scope parameter on API call for Poshi tests

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
