### PR TITLE
Workflow Automated Test - LRQA-69290 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
Just started reviewing :)

**Comment by anabuchmann** [comment]
PR sent here: https://github.com/anabuchmann/liferay-portal/pull/99

**Pull request closed without merging**
