### PR TITLE
LRQA-63476

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63476
AppBuilderWorkflow#EditFormAndTableView

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon ,

Thank you for your commit.

I've made small improvements that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/262/commits/0d9002545c41d96dd479ddec298c7e16f8314943

Great job!

**Pull request closed without merging**
