### PR TITLE
LPS-115030 Update test

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
ci:test:bundle

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/rodrigocunhaa/liferay-portal/pull/123

**Pull request closed without merging**
