### PR TITLE
Objects Automated Test - LPS-138840 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@PauloVAS ,

See: https://github.com/rodrigocunhaa/liferay-portal/pull/1027/commits/10244e41389fc379f16d3664e9ebab2913729820

I selected another option because the option you selected is the one that already comes when creating the Object through the API macro.

Thanks!

**Comment by PauloVAS** [comment]
@rodrigocunhaa Ok, thank you!

**Pull request closed without merging**
