### PR TITLE
LRQA-63477 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
AppBuilderWorkflow#OpenFormViewOnNewStep
https://issues.liferay.com/browse/LRQA-63477

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thank you for this commit @nkkwon. I've just made some small adjustments that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/274/commits/8d657ec10396cfad6f9c1a6e9647698e8476ab0b

Great job!

**Pull request closed without merging**
