### PR TITLE
LRQA-59711 - Fix KaleoformsUsecase#CompleteProcessAndAssertFieldOrder test

### PR DESCRIPTION
**Pull request by anabuchmann**

### CODE REVIEW

**Comment by anabuchmann** [comment]
Hi @rodrigocunhaa ! I've made the changes you asked for. Could you take a look?
Thank you!

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:kaleo-forms

**Pull request closed without merging**
