### PR TITLE
LRQA-67887 - Create test stubs for Workflow Metrics - Workload By Assignee

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by anabuchmann** [comment]
ci:test:sf

**Comment by anabuchmann** [comment]
ci:test:sf

**Comment by anabuchmann** [comment]
ci:stop

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Fixed SF here: https://github.com/rodrigocunhaa/liferay-portal/pull/448

**Pull request closed without merging**
