### PR TITLE
LRQA-61972 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-61972
AppBuilder#UseExistingFieldSet 
There were some scenarios that aren't able to be tested

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @nkkwon , could you please check the changes that I requested? Also, there is a PR of Calvin that is under CI testing to be sent to BChan, could you please rebase your changes with this PR: https://github.com/rodrigocunhaa/liferay-portal/pull/214. Some macros and paths that you implemented were already implemented by him which will cause conflicts. And last, could you please let me know what were the scenarios that you weren't able to test?

Thank you so much!

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Great job @nkkwon, I've fixed the conflicts on the following PR: https://github.com/rodrigocunhaa/liferay-portal/pull/222

Thank you!

**Pull request closed without merging**
