### PR TITLE
LRQA-63963

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63963

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thanks for this commit @nkkwon. I've made just a small improvement that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/314/commits/ff82bcac21d0cc58ef4fe3196b8bb5732c50067b.

There is already a macro to create a basic Workflow App with one extra step.

Thanks again and good job!

**Pull request closed without merging**
