### PR TITLE
LRQA-55167 - AppBuilder Test Fix

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by barrosdennys** [comment]
ci:test:app-builder

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by barrosdennys** [comment]
ci:test:relevant

**Comment by barrosdennys** [comment]
ci:test:stop

**Comment by barrosdennys** [comment]
ci:test:app-builder

**Comment by barrosdennys** [comment]
ci:test:relevant

**Pull request closed without merging**
