### PR TITLE
LRQA-63962 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63962

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon,

Great job. You just forgot to add the acceptance property, so I've done it here: https://github.com/rodrigocunhaa/liferay-portal/pull/324/commits/ed3735bd4d0babf30f9009c73907c29aff09e62e

Thanks!

**Pull request closed without merging**
