### PR TITLE
LRQA-68627 - Change date range dropdown path

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:workflow-metrics:nocompile

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @lucasperj ,

Your change impacted the `WorkflowMetricsCompletionVelocity#LabelFromYesterdayFilter` (see: https://testray.liferay.com/home/-/testray/case_results/1548971076) test.

Could you please check it?

Thanks!

**Comment by lucasperj** [comment]
> Hi @lucasperj ,
> 
> Your change impacted the `WorkflowMetricsCompletionVelocity#LabelFromYesterdayFilter` (see: https://testray.liferay.com/home/-/testray/case_results/1548971076) test.
> 
> Could you please check it?
> 
> Thanks!

@rodrigocunhaa  Fixed!

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:workflow-metrics

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
