### PR TITLE
LRQA 63567 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63567

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @calvinctvo , It is missing the scenario #2 which is to create a new custom object and make sure you can reuse the fieldset from the first custom object. Please, add this scenarios and resend. Thanks!

**Pull request closed without merging**
