### PR TITLE
Automated Test - LRQA-67511 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
Fixed conflicts on 
modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/paths/WorkflowMetricsProcessListView.path

**Comment by CalumR23** [comment]
Please resolve conflicts then re commit

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Fixed conflicts.

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
Forwared to BChan [Pull Request](https://github.com/CalumR23/liferay-portal/pull/6)

**Pull request closed without merging**
