### PR TITLE
LRQA 63238 | Master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63238

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @calvinctvo ,

Thank you for this commit. I've made just some small adjustments to remove the part that is not necessary for the steps that I mentioned on [LRQA-63238](https://issues.liferay.com/browse/LRQA-63238?focusedCommentId=2329959&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2329959).

You can check it here: https://github.com/rodrigocunhaa/liferay-portal/pull/252/commits/14d949655d6a47e77dfe8ed8f69bb41fec175573

Great job and keep up the good work!

**Pull request closed without merging**
