### PR TITLE
master-qa-53650-1

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-53650

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thank you @melodywu , great job! (:

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by melodywu** [comment]
Thank you so much for your help

**Pull request closed without merging**
