### PR TITLE
Workflow Automated Test - LRQA-67732 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
[Sent to BChan](https://github.com/CalumR23/liferay-portal/pull/14)

**Comment by CalumR23** [comment]
@leticiachiu this testcase fails on relevant with 
`[exec]     BUILD FAILED: Element is not present at "//div[contains(@class,'tooltip-inner') and contains(.,'task1, task2, task3')]"
     [exec]     /opt/dev/projects/github/liferay-portal/modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsAllItemsList.testcase[TooltipDisplaysBulletListWhenMultipleItems]:1880
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.WorkflowMetricsAllItemsList#TooltipDisplaysBulletListWhenMultipleItems] STANDARD_ERROR
     [exec]     java.lang.Exception: Element is not present at "//div[contains(@class,'tooltip-inner') and contains(.,'task1, task2, task3')]"
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4643)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4678)
     [exec]     	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForElementPresent(BaseWebDriverImpl.java:3357)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1192)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)`

**Comment by CalumR23** [comment]
Could you please make the changes to have this work as intended?

**Comment by leticiachiu** [comment]
@CalumR23 fixed :)

**Comment by leticiachiu** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
Just started reviewing :)

**Pull request closed without merging**
