### PR TITLE
LRQA-58283

### PR DESCRIPTION
**Pull request by kenjiheigel**
@rodrigocunhaa, @manoelcyreno, just fyi that we have a maxIterations parameter, so I didn't need to bake anything into Poshi. Please use this where applicable, thanks!
https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi-runner/poshi-script.markdown#while-loops

@hhuijser, @ling-alan-huang, BChan wants SF to ensure that the bad pattern doesn't happen again (brianchandotcom#88172 (comment)).

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@rodrigocunhaa, @manoelcyreno, just fyi that we have a `maxIterations` parameter, so I didn't need to bake anything into Poshi.  
https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi-runner/poshi-script.markdown#while-loops

@hhuijser, @ling-alan-huang, BChan wants SF to ensure that the bad pattern doesn't happen again (https://github.com/brianchandotcom/liferay-portal/pull/88172#issuecomment-621386022).

**Comment by kenjiheigel** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
cc: @palomaanunes

**Comment by palomaanunes** [comment]
hey @manoelcyreno, thank you for tagging us!

**Comment by rodrigocunhaa** [comment]
This PR had conflicts. I've just created a new one: https://github.com/rodrigocunhaa/liferay-portal/pull/45

**Pull request closed without merging**
