### PR TITLE
LRQA-63565 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63565

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Review by rodrigocunhaa — APPROVED** [review]
Great job @calvinctvo.

No adjustments needed.

Keep up the good work!

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
