### PR TITLE
LRQA-59534 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-59534
AppBuilder#ViewFormViewRules

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
ci:test:sf

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @nkkwon , please, run the SF command to fix the SF issues.

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:app-builder

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Review by rodrigocunhaa — APPROVED** [review]

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
