### PR TITLE
Objects Automated Test - LPS-145711, LPS-145712, LPS-145713, LPS-145714 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-145711
https://issues.liferay.com/browse/LPS-145712
https://issues.liferay.com/browse/LPS-145713
https://issues.liferay.com/browse/LPS-145714

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Rebase fix: https://github.com/rodrigocunhaa/liferay-portal/pull/1539

**Pull request closed without merging**
