### PR TITLE
Objects Automated Test - LPS-145717 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-145717

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by andreefarias** [comment]
ci:help

**Comment by andreefarias** [comment]
ci:reopen

**Pull request closed without merging**
