### PR TITLE
Workflow Automated Test - LRQA-68326 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @AfonsoHSantos, please add the following step to your test: 
"4. Assert that the sidebar contains Details and Revision History tabs"

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
> Hi @AfonsoHSantos, please add the following step to your test:
> "4. Assert that the sidebar contains Details and Revision History tabs"

fixed.

**Comment by brittneyq** [comment]
Combined and sent in [104425](https://github.com/brianchandotcom/liferay-portal/pull/104425)

**Pull request closed without merging**
