### PR TITLE
LRQA-63174

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63174
AppBuilderWorkflow#CreateObjectAndForm

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thanks for your commit @nkkwon. I've just made some small adjustments here: https://github.com/rodrigocunhaa/liferay-portal/pull/259/commits/2d4a32a195cace5b15d9e265cf4fee7a0e3b0c1c

Great job!

**Pull request closed without merging**
