### PR TITLE
LRQA 63627 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63627

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by guipfreire** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thanks Calvin. I fixed the conflicts here: https://github.com/rodrigocunhaa/liferay-portal/pull/306

Great job!

**Pull request closed without merging**
