### PR TITLE
Objects Automated Test - LPS-147735, LPS-147736 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-147735
https://issues.liferay.com/browse/LPS-147736

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @andreefarias ,

Please, see my comments and make the necessary changes.

Thanks!

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
