### PR TITLE
LRQA-63174

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRQA-63174

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon ,

The Object and Form need to be created inside the Workflow App Builder.

I uploaded a video on LRQA-63174.

Let me know if you have any question.

**Pull request closed without merging**
