### PR TITLE
LRQA-63541 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-63541

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
