### PR TITLE
LRQA 64123 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-64123

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by guipfreire** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Thanks @calvinctvo , great job. Since I took a long time to review it, it got some conflicts but I fixed it here: https://github.com/rodrigocunhaa/liferay-portal/pull/301

**Pull request closed without merging**
