### PR TITLE
Workflow Automated Test - LRQA-68701 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @PauloVAS, could you please add 9. Assert content page is in pending status after you add a heading fragment? Thank you! :D

**Comment by PauloVAS** [comment]
@brittneyq, fixed!

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:forward

**Pull request closed without merging**
