### PR TITLE
LRQA-67889 - Create test stubs for Workflow Metrics - Completion Velocity

### PR DESCRIPTION
**Pull request by LucasAcacio**

### CODE REVIEW

**Comment by anabuchmann** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
SF fixed here: https://github.com/rodrigocunhaa/liferay-portal/pull/442

**Pull request closed without merging**
