### PR TITLE
LPS-120475 Update WorkflowAllItems#WORKFLOW_ALL_ITEMS_FILTER_BY path selector

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by albinojunior** [comment]
ci:test:sf

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:relevant

**Comment by albinojunior** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
