### PR TITLE
Objects Automated Test - LPS-138807 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@PauloVAS ,

See a simpler way: https://github.com/rodrigocunhaa/liferay-portal/pull/1013/files

**Pull request closed without merging**
