### PR TITLE
LRQA-63175 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
AppBuilderWorkflow#CancelCreationOfObjectAndForm
https://issues.liferay.com/browse/LRQA-63175

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:stable

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon , thanks for this commit. I've just made some small adjustments that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/299/commits/8fb1a6e24f9c9bcec4fb1d70d6cdfd03340808f2.

Great job!

**Pull request closed without merging**
