### PR TITLE
Objects Automated Test - LPS-141596 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-141596

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Resent here: https://github.com/rodrigocunhaa/liferay-portal/pull/1306

**Comment by rodrigocunhaa** [comment]
Hi @andreefarias ,

Great job!

I've just done a small change on your test that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/1306/commits/872dde0ed12fa3efdb32bdec8d2fb1b18a8ab20f

We should try to use the navigation via URL whenever possible.

Thanks!

**Pull request closed without merging**
