### PR TITLE
LPS-117964 Update Poshi tests

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Made some adjustments here: https://github.com/rodrigocunhaa/liferay-portal/pull/160

**Pull request closed without merging**
