### PR TITLE
LRQA 64406 | Master

### PR DESCRIPTION
**Pull request by CalumR23**
[LRQA-64406](https://issues.liferay.com/browse/LRQA-64406)

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @CalumR23 , thank your for that. There are only a few adjustments that I made here: https://github.com/rodrigocunhaa/liferay-portal/pull/328/commits/535b5ccf472c3507afd3e864eef81574d0f9e1cc

Great job!

**Pull request closed without merging**
