### PR TITLE
LRQA 63567 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-63567

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Great job, thanks @calvinctvo

**Pull request closed without merging**
