### PR TITLE
Objects Automated Test - LPS-138804 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@PauloVAS ,

See: https://github.com/rodrigocunhaa/liferay-portal/pull/1005/commits/1a639d3649b05c201d56a441c67cd49f806d9311

**Comment by PauloVAS** [comment]
@rodrigocunhaa, thanks!

**Pull request closed without merging**
