### PR TITLE
LRQA 57664 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRQA-57664

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @calvinctvo , you did a great job here. I've just made a small adjustment that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/125/commits/0e67496b812be6cc6eeca17c72c43f060e7492a7. When filtering for "Completed" tasks, I validated that the instances are present.

Thank you very much!

**Pull request closed without merging**
