### PR TITLE
 Automated Test - LPS-147758 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**
https://issues.liferay.com/browse/LPS-147758
https://issues.liferay.com/browse/LPS-147759

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Hi @evanilson-santana , rebase error. Please, fix it. Thanks!

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by evanilson-santana** [comment]
ci:forward

**Pull request closed without merging**
