### PR TITLE
LRQA-55451

### PR DESCRIPTION
**Pull request by Adriverforlife**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Hi @Adriverforlife, Could you please do a rebase again? It has conflicts.

**Comment by Adriverforlife** [comment]
@rodrigocunhaa Done!

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:workflow

**Comment by rodrigocunhaa** [comment]
Thank you for this commit @Adriverforlife. I've just made some small changes (https://github.com/rodrigocunhaa/liferay-portal/pull/68).

**Pull request closed without merging**
