### PR TITLE
Automated Test - LRQA-67805 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/LRQA-67805, cc: @rodrigocunhaa

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @91nilo ,

Great job!

It was missing 2 steps but it was my fault that forgot to add them on the description.

I updated here: https://github.com/rodrigocunhaa/liferay-portal/pull/525

Thanks!

**Pull request closed without merging**
