### PR TITLE
master-qa-53661

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-53661

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @melodywu , I've made just a small change that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/128/commits/1206b093428f7eda3c332a88cc4f260fff2c8b1a. Actually It was my mistake when reviewing the Test steps Design you suggested. Regarding the scenario "Validate if, the SLA form, the Duration Time section should have the title updated to Duration", it was only to check that when filling the SLA, the field "Duration" is actually named "Duration" (before this story, it was named "Duration Time"). As I said, my mistake, sorry about that.

Anyway, that was a great job you did here. Thank you so much!

**Comment by melodywu** [comment]
Thank you so much Rodrigo for your review.

**Pull request closed without merging**
