### PR TITLE
LRQA-68880 Update test suite's names to singular/plural to match its folder's name

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Hi @patriciajeanperez, @brianwulbern, and @austinchiang.

Brian asked me to update all the test suite's name to singular or plural to match with its folder's name (see: https://github.com/brianchandotcom/liferay-portal/pull/104584#issuecomment-883802229)

After looking through all the test suites, I found that the following ones are not matching: 

- Account
- Translation
- Document

Could you please review this PR and let me know if you are all okay with this change?

Thanks!

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
LGTM. Thank you, @rodrigocunhaa!

**Comment by austinchiang** [comment]
LGTM, thanks @rodrigocunhaa !

**Comment by brianwulbern** [comment]
Nice work, @rodrigocunhaa - thanks for the ping and sending this through!

**Comment by rodrigocunhaa** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Thank you all (:

**Comment by rodrigocunhaa** [comment]
ci:forward

**Pull request closed without merging**
