### PR TITLE
Workflow Automated Test - LRQA-67510 | master

### PR DESCRIPTION
**Pull request by LucasAcacio**

### CODE REVIEW

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by rodrigocunhaa — CHANGES_REQUESTED** [review]
Hi @LucasAcacio ,

This test is actually way more complex than that. I updated the Test Steps on the ticket, please check it out.

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @LucasAcacio ,

I've made some small adjustments that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/461/commits/5e000fc387288c2842599e7b9f8f0c56fbc6eddd

Thanks!

**Pull request closed without merging**
