### PR TITLE
Workflow Automated Test - LRQA-69103 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Combined PR: https://github.com/rodrigocunhaa/liferay-portal/pull/869

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Pull request closed without merging**
