### PR TITLE
Workflow Automated Test - LRQA-67512 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
@CalumR23 @AfonsoHSantos , I fixed the conflits here: https://github.com/rodrigocunhaa/liferay-portal/pull/508

**Pull request closed without merging**
