### PR TITLE
Automated Test - LRQA-67614  | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/LRQA-67614, cc: @rodrigocunhaa

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by lucasperj** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Fixed conflicts here: https://github.com/rodrigocunhaa/liferay-portal/pull/505

**Pull request closed without merging**
