### PR TITLE
LRQA-63248 | Master

### PR DESCRIPTION
**Pull request by nkkwon**
AppBuilderWorkflow#CancelCreationOfFormView
https://issues.liferay.com/browse/LRQA-63248

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by rodrigocunhaa** [comment]
Hi @nkkwon , thanks for your commit. I've made just some small improvements that you can check here: https://github.com/rodrigocunhaa/liferay-portal/pull/264/commits/b7c487442607a6dd7cc1007cd5f3dc548c8dcd85.

Great job!

**Pull request closed without merging**
